// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: CanalProtocol.proto

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace com.alibaba.otter.canal.protocol
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Packet : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"magic_number")]
        [global::System.ComponentModel.DefaultValue(17)]
        public int MagicNumber
        {
            get { return __pbn__MagicNumber ?? 17; }
            set { __pbn__MagicNumber = value; }
        }
        public bool ShouldSerializeMagicNumber() => __pbn__MagicNumber != null;
        public void ResetMagicNumber() => __pbn__MagicNumber = null;
        private int? __pbn__MagicNumber;

        [global::ProtoBuf.ProtoMember(2, Name = @"version")]
        [global::System.ComponentModel.DefaultValue(1)]
        public int Version
        {
            get { return __pbn__Version ?? 1; }
            set { __pbn__Version = value; }
        }
        public bool ShouldSerializeVersion() => __pbn__Version != null;
        public void ResetVersion() => __pbn__Version = null;
        private int? __pbn__Version;

        [global::ProtoBuf.ProtoMember(3, Name = @"type")]
        [global::System.ComponentModel.DefaultValue(PacketType.Handshake)]
        public PacketType Type
        {
            get { return __pbn__Type ?? PacketType.Handshake; }
            set { __pbn__Type = value; }
        }
        public bool ShouldSerializeType() => __pbn__Type != null;
        public void ResetType() => __pbn__Type = null;
        private PacketType? __pbn__Type;

        [global::ProtoBuf.ProtoMember(4, Name = @"compression")]
        [global::System.ComponentModel.DefaultValue(Compression.None)]
        public Compression Compression
        {
            get { return __pbn__Compression ?? Compression.None; }
            set { __pbn__Compression = value; }
        }
        public bool ShouldSerializeCompression() => __pbn__Compression != null;
        public void ResetCompression() => __pbn__Compression = null;
        private Compression? __pbn__Compression;

        [global::ProtoBuf.ProtoMember(5, Name = @"body")]
        public byte[] Body
        {
            get { return __pbn__Body; }
            set { __pbn__Body = value; }
        }
        public bool ShouldSerializeBody() => __pbn__Body != null;
        public void ResetBody() => __pbn__Body = null;
        private byte[] __pbn__Body;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HeartBeat : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"send_timestamp")]
        public long SendTimestamp
        {
            get { return __pbn__SendTimestamp.GetValueOrDefault(); }
            set { __pbn__SendTimestamp = value; }
        }
        public bool ShouldSerializeSendTimestamp() => __pbn__SendTimestamp != null;
        public void ResetSendTimestamp() => __pbn__SendTimestamp = null;
        private long? __pbn__SendTimestamp;

        [global::ProtoBuf.ProtoMember(2, Name = @"start_timestamp")]
        public long StartTimestamp
        {
            get { return __pbn__StartTimestamp.GetValueOrDefault(); }
            set { __pbn__StartTimestamp = value; }
        }
        public bool ShouldSerializeStartTimestamp() => __pbn__StartTimestamp != null;
        public void ResetStartTimestamp() => __pbn__StartTimestamp = null;
        private long? __pbn__StartTimestamp;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Handshake : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"communication_encoding")]
        [global::System.ComponentModel.DefaultValue(@"utf8")]
        public string CommunicationEncoding
        {
            get { return __pbn__CommunicationEncoding ?? @"utf8"; }
            set { __pbn__CommunicationEncoding = value; }
        }
        public bool ShouldSerializeCommunicationEncoding() => __pbn__CommunicationEncoding != null;
        public void ResetCommunicationEncoding() => __pbn__CommunicationEncoding = null;
        private string __pbn__CommunicationEncoding;

        [global::ProtoBuf.ProtoMember(2, Name = @"seeds")]
        public byte[] Seeds
        {
            get { return __pbn__Seeds; }
            set { __pbn__Seeds = value; }
        }
        public bool ShouldSerializeSeeds() => __pbn__Seeds != null;
        public void ResetSeeds() => __pbn__Seeds = null;
        private byte[] __pbn__Seeds;

        [global::ProtoBuf.ProtoMember(3, Name = @"supported_compressions")]
        public global::System.Collections.Generic.List<Compression> SupportedCompressions { get; } = new global::System.Collections.Generic.List<Compression>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ClientAuth : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"username")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Username
        {
            get { return __pbn__Username ?? ""; }
            set { __pbn__Username = value; }
        }
        public bool ShouldSerializeUsername() => __pbn__Username != null;
        public void ResetUsername() => __pbn__Username = null;
        private string __pbn__Username;

        [global::ProtoBuf.ProtoMember(2, Name = @"password")]
        public byte[] Password
        {
            get { return __pbn__Password; }
            set { __pbn__Password = value; }
        }
        public bool ShouldSerializePassword() => __pbn__Password != null;
        public void ResetPassword() => __pbn__Password = null;
        private byte[] __pbn__Password;

        [global::ProtoBuf.ProtoMember(3, Name = @"net_read_timeout")]
        [global::System.ComponentModel.DefaultValue(0)]
        public int NetReadTimeout
        {
            get { return __pbn__NetReadTimeout ?? 0; }
            set { __pbn__NetReadTimeout = value; }
        }
        public bool ShouldSerializeNetReadTimeout() => __pbn__NetReadTimeout != null;
        public void ResetNetReadTimeout() => __pbn__NetReadTimeout = null;
        private int? __pbn__NetReadTimeout;

        [global::ProtoBuf.ProtoMember(4, Name = @"net_write_timeout")]
        [global::System.ComponentModel.DefaultValue(0)]
        public int NetWriteTimeout
        {
            get { return __pbn__NetWriteTimeout ?? 0; }
            set { __pbn__NetWriteTimeout = value; }
        }
        public bool ShouldSerializeNetWriteTimeout() => __pbn__NetWriteTimeout != null;
        public void ResetNetWriteTimeout() => __pbn__NetWriteTimeout = null;
        private int? __pbn__NetWriteTimeout;

        [global::ProtoBuf.ProtoMember(5, Name = @"destination")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Destination
        {
            get { return __pbn__Destination ?? ""; }
            set { __pbn__Destination = value; }
        }
        public bool ShouldSerializeDestination() => __pbn__Destination != null;
        public void ResetDestination() => __pbn__Destination = null;
        private string __pbn__Destination;

        [global::ProtoBuf.ProtoMember(6, Name = @"client_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ClientId
        {
            get { return __pbn__ClientId ?? ""; }
            set { __pbn__ClientId = value; }
        }
        public bool ShouldSerializeClientId() => __pbn__ClientId != null;
        public void ResetClientId() => __pbn__ClientId = null;
        private string __pbn__ClientId;

        [global::ProtoBuf.ProtoMember(7, Name = @"filter")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Filter
        {
            get { return __pbn__Filter ?? ""; }
            set { __pbn__Filter = value; }
        }
        public bool ShouldSerializeFilter() => __pbn__Filter != null;
        public void ResetFilter() => __pbn__Filter = null;
        private string __pbn__Filter;

        [global::ProtoBuf.ProtoMember(8, Name = @"start_timestamp")]
        public long StartTimestamp
        {
            get { return __pbn__StartTimestamp.GetValueOrDefault(); }
            set { __pbn__StartTimestamp = value; }
        }
        public bool ShouldSerializeStartTimestamp() => __pbn__StartTimestamp != null;
        public void ResetStartTimestamp() => __pbn__StartTimestamp = null;
        private long? __pbn__StartTimestamp;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Ack : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"error_code")]
        [global::System.ComponentModel.DefaultValue(0)]
        public int ErrorCode
        {
            get { return __pbn__ErrorCode ?? 0; }
            set { __pbn__ErrorCode = value; }
        }
        public bool ShouldSerializeErrorCode() => __pbn__ErrorCode != null;
        public void ResetErrorCode() => __pbn__ErrorCode = null;
        private int? __pbn__ErrorCode;

        [global::ProtoBuf.ProtoMember(2, Name = @"error_message")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ErrorMessage
        {
            get { return __pbn__ErrorMessage ?? ""; }
            set { __pbn__ErrorMessage = value; }
        }
        public bool ShouldSerializeErrorMessage() => __pbn__ErrorMessage != null;
        public void ResetErrorMessage() => __pbn__ErrorMessage = null;
        private string __pbn__ErrorMessage;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ClientAck : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"destination")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Destination
        {
            get { return __pbn__Destination ?? ""; }
            set { __pbn__Destination = value; }
        }
        public bool ShouldSerializeDestination() => __pbn__Destination != null;
        public void ResetDestination() => __pbn__Destination = null;
        private string __pbn__Destination;

        [global::ProtoBuf.ProtoMember(2, Name = @"client_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ClientId
        {
            get { return __pbn__ClientId ?? ""; }
            set { __pbn__ClientId = value; }
        }
        public bool ShouldSerializeClientId() => __pbn__ClientId != null;
        public void ResetClientId() => __pbn__ClientId = null;
        private string __pbn__ClientId;

        [global::ProtoBuf.ProtoMember(3, Name = @"batch_id")]
        public long BatchId
        {
            get { return __pbn__BatchId.GetValueOrDefault(); }
            set { __pbn__BatchId = value; }
        }
        public bool ShouldSerializeBatchId() => __pbn__BatchId != null;
        public void ResetBatchId() => __pbn__BatchId = null;
        private long? __pbn__BatchId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Sub : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"destination")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Destination
        {
            get { return __pbn__Destination ?? ""; }
            set { __pbn__Destination = value; }
        }
        public bool ShouldSerializeDestination() => __pbn__Destination != null;
        public void ResetDestination() => __pbn__Destination = null;
        private string __pbn__Destination;

        [global::ProtoBuf.ProtoMember(2, Name = @"client_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ClientId
        {
            get { return __pbn__ClientId ?? ""; }
            set { __pbn__ClientId = value; }
        }
        public bool ShouldSerializeClientId() => __pbn__ClientId != null;
        public void ResetClientId() => __pbn__ClientId = null;
        private string __pbn__ClientId;

        [global::ProtoBuf.ProtoMember(7, Name = @"filter")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Filter
        {
            get { return __pbn__Filter ?? ""; }
            set { __pbn__Filter = value; }
        }
        public bool ShouldSerializeFilter() => __pbn__Filter != null;
        public void ResetFilter() => __pbn__Filter = null;
        private string __pbn__Filter;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Unsub : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"destination")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Destination
        {
            get { return __pbn__Destination ?? ""; }
            set { __pbn__Destination = value; }
        }
        public bool ShouldSerializeDestination() => __pbn__Destination != null;
        public void ResetDestination() => __pbn__Destination = null;
        private string __pbn__Destination;

        [global::ProtoBuf.ProtoMember(2, Name = @"client_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ClientId
        {
            get { return __pbn__ClientId ?? ""; }
            set { __pbn__ClientId = value; }
        }
        public bool ShouldSerializeClientId() => __pbn__ClientId != null;
        public void ResetClientId() => __pbn__ClientId = null;
        private string __pbn__ClientId;

        [global::ProtoBuf.ProtoMember(7, Name = @"filter")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Filter
        {
            get { return __pbn__Filter ?? ""; }
            set { __pbn__Filter = value; }
        }
        public bool ShouldSerializeFilter() => __pbn__Filter != null;
        public void ResetFilter() => __pbn__Filter = null;
        private string __pbn__Filter;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Get : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"destination")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Destination
        {
            get { return __pbn__Destination ?? ""; }
            set { __pbn__Destination = value; }
        }
        public bool ShouldSerializeDestination() => __pbn__Destination != null;
        public void ResetDestination() => __pbn__Destination = null;
        private string __pbn__Destination;

        [global::ProtoBuf.ProtoMember(2, Name = @"client_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ClientId
        {
            get { return __pbn__ClientId ?? ""; }
            set { __pbn__ClientId = value; }
        }
        public bool ShouldSerializeClientId() => __pbn__ClientId != null;
        public void ResetClientId() => __pbn__ClientId = null;
        private string __pbn__ClientId;

        [global::ProtoBuf.ProtoMember(3, Name = @"fetch_size")]
        public int FetchSize
        {
            get { return __pbn__FetchSize.GetValueOrDefault(); }
            set { __pbn__FetchSize = value; }
        }
        public bool ShouldSerializeFetchSize() => __pbn__FetchSize != null;
        public void ResetFetchSize() => __pbn__FetchSize = null;
        private int? __pbn__FetchSize;

        [global::ProtoBuf.ProtoMember(4, Name = @"timeout")]
        [global::System.ComponentModel.DefaultValue(-1)]
        public long Timeout
        {
            get { return __pbn__Timeout ?? -1; }
            set { __pbn__Timeout = value; }
        }
        public bool ShouldSerializeTimeout() => __pbn__Timeout != null;
        public void ResetTimeout() => __pbn__Timeout = null;
        private long? __pbn__Timeout;

        [global::ProtoBuf.ProtoMember(5, Name = @"unit")]
        [global::System.ComponentModel.DefaultValue(2)]
        public int Unit
        {
            get { return __pbn__Unit ?? 2; }
            set { __pbn__Unit = value; }
        }
        public bool ShouldSerializeUnit() => __pbn__Unit != null;
        public void ResetUnit() => __pbn__Unit = null;
        private int? __pbn__Unit;

        [global::ProtoBuf.ProtoMember(6, Name = @"auto_ack")]
        [global::System.ComponentModel.DefaultValue(false)]
        public bool AutoAck
        {
            get { return __pbn__AutoAck ?? false; }
            set { __pbn__AutoAck = value; }
        }
        public bool ShouldSerializeAutoAck() => __pbn__AutoAck != null;
        public void ResetAutoAck() => __pbn__AutoAck = null;
        private bool? __pbn__AutoAck;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Messages : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"batch_id")]
        public long BatchId
        {
            get { return __pbn__BatchId.GetValueOrDefault(); }
            set { __pbn__BatchId = value; }
        }
        public bool ShouldSerializeBatchId() => __pbn__BatchId != null;
        public void ResetBatchId() => __pbn__BatchId = null;
        private long? __pbn__BatchId;

        [global::ProtoBuf.ProtoMember(2)]
        public global::System.Collections.Generic.List<byte[]> messages { get; } = new global::System.Collections.Generic.List<byte[]>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Dump : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"journal")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Journal
        {
            get { return __pbn__Journal ?? ""; }
            set { __pbn__Journal = value; }
        }
        public bool ShouldSerializeJournal() => __pbn__Journal != null;
        public void ResetJournal() => __pbn__Journal = null;
        private string __pbn__Journal;

        [global::ProtoBuf.ProtoMember(2, Name = @"position")]
        public long Position
        {
            get { return __pbn__Position.GetValueOrDefault(); }
            set { __pbn__Position = value; }
        }
        public bool ShouldSerializePosition() => __pbn__Position != null;
        public void ResetPosition() => __pbn__Position = null;
        private long? __pbn__Position;

        [global::ProtoBuf.ProtoMember(3, Name = @"timestamp")]
        [global::System.ComponentModel.DefaultValue(0)]
        public long Timestamp
        {
            get { return __pbn__Timestamp ?? 0; }
            set { __pbn__Timestamp = value; }
        }
        public bool ShouldSerializeTimestamp() => __pbn__Timestamp != null;
        public void ResetTimestamp() => __pbn__Timestamp = null;
        private long? __pbn__Timestamp;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ClientRollback : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"destination")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Destination
        {
            get { return __pbn__Destination ?? ""; }
            set { __pbn__Destination = value; }
        }
        public bool ShouldSerializeDestination() => __pbn__Destination != null;
        public void ResetDestination() => __pbn__Destination = null;
        private string __pbn__Destination;

        [global::ProtoBuf.ProtoMember(2, Name = @"client_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ClientId
        {
            get { return __pbn__ClientId ?? ""; }
            set { __pbn__ClientId = value; }
        }
        public bool ShouldSerializeClientId() => __pbn__ClientId != null;
        public void ResetClientId() => __pbn__ClientId = null;
        private string __pbn__ClientId;

        [global::ProtoBuf.ProtoMember(3, Name = @"batch_id")]
        public long BatchId
        {
            get { return __pbn__BatchId.GetValueOrDefault(); }
            set { __pbn__BatchId = value; }
        }
        public bool ShouldSerializeBatchId() => __pbn__BatchId != null;
        public void ResetBatchId() => __pbn__BatchId = null;
        private long? __pbn__BatchId;

    }

    [global::ProtoBuf.ProtoContract()]
    public enum Compression
    {
        [global::ProtoBuf.ProtoEnum(Name = @"NONE")]
        None = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"ZLIB")]
        Zlib = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"GZIP")]
        Gzip = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"LZF")]
        Lzf = 4,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum PacketType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"HANDSHAKE")]
        Handshake = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"CLIENTAUTHENTICATION")]
        Clientauthentication = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"ACK")]
        Ack = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"SUBSCRIPTION")]
        Subscription = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"UNSUBSCRIPTION")]
        Unsubscription = 5,
        [global::ProtoBuf.ProtoEnum(Name = @"GET")]
        Get = 6,
        [global::ProtoBuf.ProtoEnum(Name = @"MESSAGES")]
        Messages = 7,
        [global::ProtoBuf.ProtoEnum(Name = @"CLIENTACK")]
        Clientack = 8,
        [global::ProtoBuf.ProtoEnum(Name = @"SHUTDOWN")]
        Shutdown = 9,
        [global::ProtoBuf.ProtoEnum(Name = @"DUMP")]
        Dump = 10,
        [global::ProtoBuf.ProtoEnum(Name = @"HEARTBEAT")]
        Heartbeat = 11,
        [global::ProtoBuf.ProtoEnum(Name = @"CLIENTROLLBACK")]
        Clientrollback = 12,
    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
