// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: EntryProtocol.proto

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace com.alibaba.otter.canal.protocol
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Entry : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"header")]
        public Header Header { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue(EntryType.Rowdata)]
        public EntryType entryType
        {
            get { return __pbn__entryType ?? EntryType.Rowdata; }
            set { __pbn__entryType = value; }
        }
        public bool ShouldSerializeentryType() => __pbn__entryType != null;
        public void ResetentryType() => __pbn__entryType = null;
        private EntryType? __pbn__entryType;

        [global::ProtoBuf.ProtoMember(3)]
        public byte[] storeValue
        {
            get { return __pbn__storeValue; }
            set { __pbn__storeValue = value; }
        }
        public bool ShouldSerializestoreValue() => __pbn__storeValue != null;
        public void ResetstoreValue() => __pbn__storeValue = null;
        private byte[] __pbn__storeValue;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Header : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"version")]
        [global::System.ComponentModel.DefaultValue(1)]
        public int Version
        {
            get { return __pbn__Version ?? 1; }
            set { __pbn__Version = value; }
        }
        public bool ShouldSerializeVersion() => __pbn__Version != null;
        public void ResetVersion() => __pbn__Version = null;
        private int? __pbn__Version;

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string logfileName
        {
            get { return __pbn__logfileName ?? ""; }
            set { __pbn__logfileName = value; }
        }
        public bool ShouldSerializelogfileName() => __pbn__logfileName != null;
        public void ResetlogfileName() => __pbn__logfileName = null;
        private string __pbn__logfileName;

        [global::ProtoBuf.ProtoMember(3)]
        public long logfileOffset
        {
            get { return __pbn__logfileOffset.GetValueOrDefault(); }
            set { __pbn__logfileOffset = value; }
        }
        public bool ShouldSerializelogfileOffset() => __pbn__logfileOffset != null;
        public void ResetlogfileOffset() => __pbn__logfileOffset = null;
        private long? __pbn__logfileOffset;

        [global::ProtoBuf.ProtoMember(4)]
        public long serverId
        {
            get { return __pbn__serverId.GetValueOrDefault(); }
            set { __pbn__serverId = value; }
        }
        public bool ShouldSerializeserverId() => __pbn__serverId != null;
        public void ResetserverId() => __pbn__serverId = null;
        private long? __pbn__serverId;

        [global::ProtoBuf.ProtoMember(5)]
        [global::System.ComponentModel.DefaultValue("")]
        public string serverenCode
        {
            get { return __pbn__serverenCode ?? ""; }
            set { __pbn__serverenCode = value; }
        }
        public bool ShouldSerializeserverenCode() => __pbn__serverenCode != null;
        public void ResetserverenCode() => __pbn__serverenCode = null;
        private string __pbn__serverenCode;

        [global::ProtoBuf.ProtoMember(6)]
        public long executeTime
        {
            get { return __pbn__executeTime.GetValueOrDefault(); }
            set { __pbn__executeTime = value; }
        }
        public bool ShouldSerializeexecuteTime() => __pbn__executeTime != null;
        public void ResetexecuteTime() => __pbn__executeTime = null;
        private long? __pbn__executeTime;

        [global::ProtoBuf.ProtoMember(7)]
        [global::System.ComponentModel.DefaultValue(Type.Mysql)]
        public Type sourceType
        {
            get { return __pbn__sourceType ?? Type.Mysql; }
            set { __pbn__sourceType = value; }
        }
        public bool ShouldSerializesourceType() => __pbn__sourceType != null;
        public void ResetsourceType() => __pbn__sourceType = null;
        private Type? __pbn__sourceType;

        [global::ProtoBuf.ProtoMember(8)]
        [global::System.ComponentModel.DefaultValue("")]
        public string schemaName
        {
            get { return __pbn__schemaName ?? ""; }
            set { __pbn__schemaName = value; }
        }
        public bool ShouldSerializeschemaName() => __pbn__schemaName != null;
        public void ResetschemaName() => __pbn__schemaName = null;
        private string __pbn__schemaName;

        [global::ProtoBuf.ProtoMember(9)]
        [global::System.ComponentModel.DefaultValue("")]
        public string tableName
        {
            get { return __pbn__tableName ?? ""; }
            set { __pbn__tableName = value; }
        }
        public bool ShouldSerializetableName() => __pbn__tableName != null;
        public void ResettableName() => __pbn__tableName = null;
        private string __pbn__tableName;

        [global::ProtoBuf.ProtoMember(10)]
        public long eventLength
        {
            get { return __pbn__eventLength.GetValueOrDefault(); }
            set { __pbn__eventLength = value; }
        }
        public bool ShouldSerializeeventLength() => __pbn__eventLength != null;
        public void ReseteventLength() => __pbn__eventLength = null;
        private long? __pbn__eventLength;

        [global::ProtoBuf.ProtoMember(11)]
        [global::System.ComponentModel.DefaultValue(EventType.Update)]
        public EventType eventType
        {
            get { return __pbn__eventType ?? EventType.Update; }
            set { __pbn__eventType = value; }
        }
        public bool ShouldSerializeeventType() => __pbn__eventType != null;
        public void ReseteventType() => __pbn__eventType = null;
        private EventType? __pbn__eventType;

        [global::ProtoBuf.ProtoMember(12, Name = @"props")]
        public global::System.Collections.Generic.List<Pair> Props { get; } = new global::System.Collections.Generic.List<Pair>();

        [global::ProtoBuf.ProtoMember(13, Name = @"gtid")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Gtid
        {
            get { return __pbn__Gtid ?? ""; }
            set { __pbn__Gtid = value; }
        }
        public bool ShouldSerializeGtid() => __pbn__Gtid != null;
        public void ResetGtid() => __pbn__Gtid = null;
        private string __pbn__Gtid;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Column : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"index")]
        public int Index
        {
            get { return __pbn__Index.GetValueOrDefault(); }
            set { __pbn__Index = value; }
        }
        public bool ShouldSerializeIndex() => __pbn__Index != null;
        public void ResetIndex() => __pbn__Index = null;
        private int? __pbn__Index;

        [global::ProtoBuf.ProtoMember(2)]
        public int sqlType
        {
            get { return __pbn__sqlType.GetValueOrDefault(); }
            set { __pbn__sqlType = value; }
        }
        public bool ShouldSerializesqlType() => __pbn__sqlType != null;
        public void ResetsqlType() => __pbn__sqlType = null;
        private int? __pbn__sqlType;

        [global::ProtoBuf.ProtoMember(3, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name
        {
            get { return __pbn__Name ?? ""; }
            set { __pbn__Name = value; }
        }
        public bool ShouldSerializeName() => __pbn__Name != null;
        public void ResetName() => __pbn__Name = null;
        private string __pbn__Name;

        [global::ProtoBuf.ProtoMember(4)]
        public bool isKey
        {
            get { return __pbn__isKey.GetValueOrDefault(); }
            set { __pbn__isKey = value; }
        }
        public bool ShouldSerializeisKey() => __pbn__isKey != null;
        public void ResetisKey() => __pbn__isKey = null;
        private bool? __pbn__isKey;

        [global::ProtoBuf.ProtoMember(5, Name = @"updated")]
        public bool Updated
        {
            get { return __pbn__Updated.GetValueOrDefault(); }
            set { __pbn__Updated = value; }
        }
        public bool ShouldSerializeUpdated() => __pbn__Updated != null;
        public void ResetUpdated() => __pbn__Updated = null;
        private bool? __pbn__Updated;

        [global::ProtoBuf.ProtoMember(6)]
        [global::System.ComponentModel.DefaultValue(false)]
        public bool isNull
        {
            get { return __pbn__isNull ?? false; }
            set { __pbn__isNull = value; }
        }
        public bool ShouldSerializeisNull() => __pbn__isNull != null;
        public void ResetisNull() => __pbn__isNull = null;
        private bool? __pbn__isNull;

        [global::ProtoBuf.ProtoMember(7, Name = @"props")]
        public global::System.Collections.Generic.List<Pair> Props { get; } = new global::System.Collections.Generic.List<Pair>();

        [global::ProtoBuf.ProtoMember(8, Name = @"value")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Value
        {
            get { return __pbn__Value ?? ""; }
            set { __pbn__Value = value; }
        }
        public bool ShouldSerializeValue() => __pbn__Value != null;
        public void ResetValue() => __pbn__Value = null;
        private string __pbn__Value;

        [global::ProtoBuf.ProtoMember(9, Name = @"length")]
        public int Length
        {
            get { return __pbn__Length.GetValueOrDefault(); }
            set { __pbn__Length = value; }
        }
        public bool ShouldSerializeLength() => __pbn__Length != null;
        public void ResetLength() => __pbn__Length = null;
        private int? __pbn__Length;

        [global::ProtoBuf.ProtoMember(10)]
        [global::System.ComponentModel.DefaultValue("")]
        public string mysqlType
        {
            get { return __pbn__mysqlType ?? ""; }
            set { __pbn__mysqlType = value; }
        }
        public bool ShouldSerializemysqlType() => __pbn__mysqlType != null;
        public void ResetmysqlType() => __pbn__mysqlType = null;
        private string __pbn__mysqlType;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RowData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public global::System.Collections.Generic.List<Column> beforeColumns { get; } = new global::System.Collections.Generic.List<Column>();

        [global::ProtoBuf.ProtoMember(2)]
        public global::System.Collections.Generic.List<Column> afterColumns { get; } = new global::System.Collections.Generic.List<Column>();

        [global::ProtoBuf.ProtoMember(3, Name = @"props")]
        public global::System.Collections.Generic.List<Pair> Props { get; } = new global::System.Collections.Generic.List<Pair>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RowChange : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long tableId
        {
            get { return __pbn__tableId.GetValueOrDefault(); }
            set { __pbn__tableId = value; }
        }
        public bool ShouldSerializetableId() => __pbn__tableId != null;
        public void ResettableId() => __pbn__tableId = null;
        private long? __pbn__tableId;

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue(EventType.Update)]
        public EventType eventType
        {
            get { return __pbn__eventType ?? EventType.Update; }
            set { __pbn__eventType = value; }
        }
        public bool ShouldSerializeeventType() => __pbn__eventType != null;
        public void ReseteventType() => __pbn__eventType = null;
        private EventType? __pbn__eventType;

        [global::ProtoBuf.ProtoMember(10)]
        [global::System.ComponentModel.DefaultValue(false)]
        public bool isDdl
        {
            get { return __pbn__isDdl ?? false; }
            set { __pbn__isDdl = value; }
        }
        public bool ShouldSerializeisDdl() => __pbn__isDdl != null;
        public void ResetisDdl() => __pbn__isDdl = null;
        private bool? __pbn__isDdl;

        [global::ProtoBuf.ProtoMember(11, Name = @"sql")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Sql
        {
            get { return __pbn__Sql ?? ""; }
            set { __pbn__Sql = value; }
        }
        public bool ShouldSerializeSql() => __pbn__Sql != null;
        public void ResetSql() => __pbn__Sql = null;
        private string __pbn__Sql;

        [global::ProtoBuf.ProtoMember(12)]
        public global::System.Collections.Generic.List<RowData> rowDatas { get; } = new global::System.Collections.Generic.List<RowData>();

        [global::ProtoBuf.ProtoMember(13, Name = @"props")]
        public global::System.Collections.Generic.List<Pair> Props { get; } = new global::System.Collections.Generic.List<Pair>();

        [global::ProtoBuf.ProtoMember(14)]
        [global::System.ComponentModel.DefaultValue("")]
        public string ddlSchemaName
        {
            get { return __pbn__ddlSchemaName ?? ""; }
            set { __pbn__ddlSchemaName = value; }
        }
        public bool ShouldSerializeddlSchemaName() => __pbn__ddlSchemaName != null;
        public void ResetddlSchemaName() => __pbn__ddlSchemaName = null;
        private string __pbn__ddlSchemaName;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TransactionBegin : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long executeTime
        {
            get { return __pbn__executeTime.GetValueOrDefault(); }
            set { __pbn__executeTime = value; }
        }
        public bool ShouldSerializeexecuteTime() => __pbn__executeTime != null;
        public void ResetexecuteTime() => __pbn__executeTime = null;
        private long? __pbn__executeTime;

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string transactionId
        {
            get { return __pbn__transactionId ?? ""; }
            set { __pbn__transactionId = value; }
        }
        public bool ShouldSerializetransactionId() => __pbn__transactionId != null;
        public void ResettransactionId() => __pbn__transactionId = null;
        private string __pbn__transactionId;

        [global::ProtoBuf.ProtoMember(3, Name = @"props")]
        public global::System.Collections.Generic.List<Pair> Props { get; } = new global::System.Collections.Generic.List<Pair>();

        [global::ProtoBuf.ProtoMember(4)]
        public long threadId
        {
            get { return __pbn__threadId.GetValueOrDefault(); }
            set { __pbn__threadId = value; }
        }
        public bool ShouldSerializethreadId() => __pbn__threadId != null;
        public void ResetthreadId() => __pbn__threadId = null;
        private long? __pbn__threadId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TransactionEnd : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long executeTime
        {
            get { return __pbn__executeTime.GetValueOrDefault(); }
            set { __pbn__executeTime = value; }
        }
        public bool ShouldSerializeexecuteTime() => __pbn__executeTime != null;
        public void ResetexecuteTime() => __pbn__executeTime = null;
        private long? __pbn__executeTime;

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string transactionId
        {
            get { return __pbn__transactionId ?? ""; }
            set { __pbn__transactionId = value; }
        }
        public bool ShouldSerializetransactionId() => __pbn__transactionId != null;
        public void ResettransactionId() => __pbn__transactionId = null;
        private string __pbn__transactionId;

        [global::ProtoBuf.ProtoMember(3, Name = @"props")]
        public global::System.Collections.Generic.List<Pair> Props { get; } = new global::System.Collections.Generic.List<Pair>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Pair : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"key")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Key
        {
            get { return __pbn__Key ?? ""; }
            set { __pbn__Key = value; }
        }
        public bool ShouldSerializeKey() => __pbn__Key != null;
        public void ResetKey() => __pbn__Key = null;
        private string __pbn__Key;

        [global::ProtoBuf.ProtoMember(2, Name = @"value")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Value
        {
            get { return __pbn__Value ?? ""; }
            set { __pbn__Value = value; }
        }
        public bool ShouldSerializeValue() => __pbn__Value != null;
        public void ResetValue() => __pbn__Value = null;
        private string __pbn__Value;

    }

    [global::ProtoBuf.ProtoContract()]
    public enum EntryType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"TRANSACTIONBEGIN")]
        Transactionbegin = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"ROWDATA")]
        Rowdata = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"TRANSACTIONEND")]
        Transactionend = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"HEARTBEAT")]
        Heartbeat = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"GTIDLOG")]
        Gtidlog = 5,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum EventType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"INSERT")]
        Insert = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"UPDATE")]
        Update = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"DELETE")]
        Delete = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"CREATE")]
        Create = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"ALTER")]
        Alter = 5,
        [global::ProtoBuf.ProtoEnum(Name = @"ERASE")]
        Erase = 6,
        [global::ProtoBuf.ProtoEnum(Name = @"QUERY")]
        Query = 7,
        [global::ProtoBuf.ProtoEnum(Name = @"TRUNCATE")]
        Truncate = 8,
        [global::ProtoBuf.ProtoEnum(Name = @"RENAME")]
        Rename = 9,
        [global::ProtoBuf.ProtoEnum(Name = @"CINDEX")]
        Cindex = 10,
        [global::ProtoBuf.ProtoEnum(Name = @"DINDEX")]
        Dindex = 11,
        [global::ProtoBuf.ProtoEnum(Name = @"GTID")]
        Gtid = 12,
        [global::ProtoBuf.ProtoEnum(Name = @"XACOMMIT")]
        Xacommit = 13,
        [global::ProtoBuf.ProtoEnum(Name = @"XAROLLBACK")]
        Xarollback = 14,
        [global::ProtoBuf.ProtoEnum(Name = @"MHEARTBEAT")]
        Mheartbeat = 15,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum Type
    {
        [global::ProtoBuf.ProtoEnum(Name = @"ORACLE")]
        Oracle = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"MYSQL")]
        Mysql = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"PGSQL")]
        Pgsql = 3,
    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
